
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/ruuvi-saver
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: "goreleaser.dockerfile"
    image_templates:
      - "ghcr.io/tuhis/ruuvi-saver:latest"
      - "ghcr.io/tuhis/ruuvi-saver:{{ .Tag }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

