---
version: '2'
services:

  influxdb:
    container_name: influxdb
    image: influxdb:2.7.6-alpine
    ports:
      - 8086:8086
    # volumes:
    #   - ./influxdb/config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: adminpassword
      DOCKER_INFLUXDB_INIT_ORG: test-org
      DOCKER_INFLUXDB_INIT_BUCKET: iot-sensor-data
